version: '3.8'

services:
  db:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: webstream
    ports:
      - '3307:3306'
    volumes:
      - mysql_data_volume:/var/lib/mysql
    networks:
      - app_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app_service

    mem_limit: 70m

    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:password@db:3306/webstream
      - PORT=3000
      - ./.env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data_volume:
